from alembic import command

from art_curator.db.models import Base
from tests.db import alembic_config, run_sql

APP_TABLES = set(Base.metadata.tables)

TABLES = "SELECT tablename FROM pg_tables WHERE schemaname = 'public'"
EXTENSIONS = "SELECT extname FROM pg_extension"


def _names(url, sql) -> set[str]:
    return {row[0] for row in run_sql(url, sql)[0]}


def test_round_trip(fresh_database):
    with fresh_database() as url:
        cfg = alembic_config(url)

        command.upgrade(cfg, "head")
        assert _names(url, TABLES) >= APP_TABLES
        assert {"postgis", "vector"} <= _names(url, EXTENSIONS)

        command.downgrade(cfg, "base")
        assert _names(url, TABLES) == {"alembic_version"}
        assert not {"postgis", "vector"} & _names(url, EXTENSIONS)

        command.upgrade(cfg, "head")
        assert _names(url, TABLES) >= APP_TABLES


def test_models_match_migrations(migrated_db):
    # Raises AutogenerateDiffsDetected if models.py and the migrations have drifted apart.
    command.check(alembic_config(migrated_db))


def test_geography_distance_is_in_metres(migrated_db):
    # CLAUDE.md § 8: distances come from PostGIS. MACBA → Fundació Joan Miró is ~2.2 km.
    [[(metres,)]] = run_sql(
        migrated_db,
        "SELECT ST_Distance("
        "  ST_GeogFromText('SRID=4326;POINT(2.1669 41.3833)'),"
        "  ST_GeogFromText('SRID=4326;POINT(2.1600 41.3685)'))",
    )
    assert 1_500 < metres < 2_500
